quarkus.http.host=127.0.0.1
quarkus.http.port=8080
quarkus.hibernate-orm.database.generation=update

llmtoolbox.auth.token=change-me
llmtoolbox.auth.admin.username=admin
llmtoolbox.auth.admin.password=admin
llmtoolbox.api-key.pepper=llmtoolbox-pepper

llmtoolbox.files.allowed-root=/opt/app
llmtoolbox.communication.telegram.token=0
llmtoolbox.communication.telegram.chatid=0
